env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
    - plugin:react-hooks/recommended
    - prettier
ignorePatterns:
    - dist
    - /*.config.js
    - /*.config.ts
    - "*.d.ts"
parser: "@typescript-eslint/parser"
plugins:
    - react
    - react-refresh
rules:
    react-hooks/rules-of-hooks: error
    react/react-in-jsx-scope: off
